In [2]:
# Problem - 1: Array Creation
import numpy as np
print("\n1. Initialize an empty array with size 2X2:")
empty_array = np.empty((2, 2))
print(empty_array)
print(f"Shape: {empty_array.shape}")
print(f"Data type: {empty_array.dtype}")

print("\n2. Initialize an all one array with size 4X2:")
ones_array = np.ones((4, 2))
print(ones_array)
print(f"Shape: {ones_array.shape}")

print("\n3. Return a new array of given shape and type, filled with fill value:")
# Create a 3x3 array filled with value 7
filled_array = np.full((3, 3), 7)
print("3x3 array filled with 7:")
print(filled_array)

# Create a 2x4 array filled with 2.5
filled_array_float = np.full((2, 4), 2.5)
print("\n2x4 array filled with 2.5:")
print(filled_array_float)

print("\n4. Return a new array of zeros with same shape and type as a given array:")
# Using the ones_array from above as reference
zeros_like_array = np.zeros_like(ones_array)
print("Original array (ones):")
print(ones_array)
print("Zeros array with same shape and type:")
print(zeros_like_array)

print("\n5. Return a new array of ones with same shape and type as a given array:")
# Using the filled_array from above as reference
ones_like_array = np.ones_like(filled_array)
print("Original array (filled with 7):")
print(filled_array)
print("Ones array with same shape and type:")
print(ones_like_array)

print("\n6. For an existing list new_list = [1,2,3,4] convert to a numpy array:")
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(f"Original list: {new_list}")
print(f"Converted numpy array: {numpy_array}")
print(f"Array shape: {numpy_array.shape}")
print(f"Array dtype: {numpy_array.dtype}", "\n")


1. Initialize an empty array with size 2X2:
[[2.12550091e-315 0.00000000e+000]
 [6.81803000e-310 6.81802999e-310]]
Shape: (2, 2)
Data type: float64

2. Initialize an all one array with size 4X2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Shape: (4, 2)

3. Return a new array of given shape and type, filled with fill value:
3x3 array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

2x4 array filled with 2.5:
[[2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]]

4. Return a new array of zeros with same shape and type as a given array:
Original array (ones):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Zeros array with same shape and type:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

5. Return a new array of ones with same shape and type as a given array:
Original array (filled with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]
Ones array with same shape and type:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

6. For an existing list new_list = [1,2,3,4] convert to a numpy array:
Original list: [1, 2, 3, 4]
Converted numpy array: [1 2 3 4]
Array shape: (4,)
A

In [3]:
#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing
import numpy as np

# 1. Create an array with values ranging from 10 to 49
print("\n1. Array with values from 10 to 49:")
arr1 = np.arange(10, 50)
print(arr1)
print(f"Shape: {arr1.shape}, Length: {len(arr1)}")

# 2. Create a 3X3 matrix with values ranging from 0 to 8
print("\n2. 3x3 matrix with values from 0 to 8:")
arr2 = np.arange(9).reshape(3, 3)
print(arr2)
print(f"Shape: {arr2.shape}")

# 3. Create a 3X3 identity matrix
print("\n3. 3x3 identity matrix:")
identity_matrix = np.eye(3)
print(identity_matrix)

# 4. Create a random array of size 30 and find the mean
print("\n4. Random array of size 30 and its mean:")
random_arr = np.random.random(30)
mean_value = random_arr.mean()
print(f"Array: {random_arr}")
print(f"Mean: {mean_value:.4f}")

# 5. Create a 10X10 array with random values and find min/max
print("\n5. 10x10 random array with min and max values:")
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("Array:")
print(random_10x10)
print(f"Minimum value: {min_value:.4f}")
print(f"Maximum value: {max_value:.4f}")

# 6. Create a zero array of size 10 and replace 5th element with 1
print("\n6. Zero array of size 10, replace 5th element with 1:")
zero_arr = np.zeros(10)
print(f"Before: {zero_arr}")
zero_arr[4] = 1  # Remember: indexing starts at 0, so 5th element is index 4
print(f"After:  {zero_arr}")

# 7. Reverse an array arr = [1,2,0,0,4,0]
print("\n7. Reverse an array [1,2,0,0,4,0]:")
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(f"Original: {arr}")
print(f"Reversed: {reversed_arr}")

# 8. Create a 2D array with 1 on border and 0 inside
print("\n8. 2D array with 1 on border and 0 inside (5x5 example):")
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0  # Set inner elements to 0
print(border_array)

# 9. Create a 8X8 matrix with checkerboard pattern
print("\n9. 8x8 checkerboard pattern:")
checkerboard = np.zeros((8, 8), dtype=int)
# Method 1: Using slicing
checkerboard[1::2, ::2] = 1  # Odd rows, even columns
checkerboard[::2, 1::2] = 1  # Even rows, odd columns
print("Checkerboard pattern:")
print(checkerboard, "\n")



1. Array with values from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Shape: (40,), Length: 40

2. 3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Shape: (3, 3)

3. 3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30 and its mean:
Array: [0.79809836 0.87210163 0.93248838 0.25525614 0.71981545 0.93206962
 0.75285609 0.39466325 0.54410338 0.91814381 0.54100439 0.64946083
 0.77260231 0.14587999 0.32986417 0.45055195 0.97599468 0.96065898
 0.96101982 0.92493255 0.7229785  0.16916388 0.26336439 0.87377246
 0.73511855 0.26927086 0.17023219 0.87137506 0.13619951 0.47672554]
Mean: 0.6173

5. 10x10 random array with min and max values:
Array:
[[0.62239622 0.00696099 0.97122054 0.42844071 0.06414967 0.91575629
  0.74353982 0.14876098 0.5880282  0.64122364]
 [0.18238861 0.18219293 0.46205541 0.39435649 0.43207336 0.57577756
  0.76827024 0.35621801 0.59804496 

In [ ]:
#Problem - 3: Array Operations
import numpy as np

# Initialize the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Initial Arrays:")
print(f"x = \n{x}")
print(f"y = \n{y}")
print(f"v = {v}")
print(f"w = {w}")
print(f"x shape: {x.shape}, y shape: {y.shape}")
print(f"v shape: {v.shape}, w shape: {w.shape}")

# 1. Add the two arrays
print("\n1. Array Addition:")
print("x + y =")
print(x + y)

# 2. Subtract the two arrays
print("\n2. Array Subtraction:")
print("x - y =")
print(x - y)
print("y - x =")
print(y - x)

# 3. Multiply the array with any integers
print("\n3. Array Multiplication with scalars:")
print("2 * x =")
print(2 * x)
print("3 * y =")
print(3 * y)
print("0.5 * v =", 0.5 * v)

# 4. Find the square of each element of the array
print("\n4. Element-wise Square:")
print("x² =")
print(x ** 2)
print("y² =")
print(y ** 2)
print("v² =", v ** 2)

# Alternative method using np.square()
print("\nUsing np.square():")
print("np.square(x) =")
print(np.square(x))

# 5. Find the dot product
print("\n5. Dot Products:")

# Dot product between v and w
dot_vw = np.dot(v, w)
print(f"v · w = {dot_vw}")
print(f"Calculation: ({v[0]}×{w[0]}) + ({v[1]}×{w[1]}) = {v[0]*w[0]} + {v[1]*w[1]} = {dot_vw}")

# Dot product between x and v
dot_xv = np.dot(x, v)
print(f"\nx · v = {dot_xv}")
print("Calculation:")
print(f"Row 1: ({x[0,0]}×{v[0]}) + ({x[0,1]}×{v[1]}) = {x[0,0]*v[0]} + {x[0,1]*v[1]} = {x[0,0]*v[0] + x[0,1]*v[1]}")
print(f"Row 2: ({x[1,0]}×{v[0]}) + ({x[1,1]}×{v[1]}) = {x[1,0]*v[0]} + {x[1,1]*v[1]} = {x[1,0]*v[0] + x[1,1]*v[1]}")

# Dot product between x and y
dot_xy = np.dot(x, y)
print(f"\nx · y = \n{dot_xy}")
print("Calculation:")
print(f"Element [0,0]: ({x[0,0]}×{y[0,0]}) + ({x[0,1]}×{y[1,0]}) = {x[0,0]*y[0,0]} + {x[0,1]*y[1,0]} = {x[0,0]*y[0,0] + x[0,1]*y[1,0]}")
print(f"Element [0,1]: ({x[0,0]}×{y[0,1]}) + ({x[0,1]}×{y[1,1]}) = {x[0,0]*y[0,1]} + {x[0,1]*y[1,1]} = {x[0,0]*y[0,1] + x[0,1]*y[1,1]}")
print(f"Element [1,0]: ({x[1,0]}×{y[0,0]}) + ({x[1,1]}×{y[1,0]}) = {x[1,0]*y[0,0]} + {x[1,1]*y[1,0]} = {x[1,0]*y[0,0] + x[1,1]*y[1,0]}")
print(f"Element [1,1]: ({x[1,0]}×{y[0,1]}) + ({x[1,1]}×{y[1,1]}) = {x[1,0]*y[0,1]} + {x[1,1]}×{y[1,1]} = {x[1,0]*y[0,1] + x[1,1]*y[1,1]}")

# 6. Concatenation
print("\n6. Array Concatenation:")

# Concatenate x and y along row (axis=0)
concat_row = np.concatenate((x, y), axis=0)
print("Concatenate x and y along rows (axis=0):")
print(concat_row)

# Alternative using vstack
concat_vstack = np.vstack((x, y))
print("\nUsing np.vstack((x, y)):")
print(concat_vstack)

# Concatenate v and w along column (axis=1)
# First we need to make them 2D arrays for column concatenation
v_2d = v.reshape(-1, 1)  # Convert to column vector
w_2d = w.reshape(-1, 1)  # Convert to column vector
concat_col = np.concatenate((v_2d, w_2d), axis=1)
print("\nConcatenate v and w along columns (axis=1):")
print(concat_col)

# Alternative using hstack
concat_hstack = np.hstack((v.reshape(-1, 1), w.reshape(-1, 1)))
print("\nUsing np.hstack for v and w:")
print(concat_hstack)

# 7. Concatenate x and v
print("\n7. Concatenate x and v:")
print(f"x shape: {x.shape}")
print(f"v shape: {v.shape}")

try:
    result = np.concatenate((x, v))
    print("Success:", result)
except ValueError as e:
    print(f"Error: {e}")
    print("Explanation: Cannot concatenate arrays with different dimensions.")
    print("x is 2D (2x2) while v is 1D (2,). They must have the same number of dimensions.")



Initial Arrays:
x = 
[[1 2]
 [3 5]]
y = 
[[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]
x shape: (2, 2), y shape: (2, 2)
v shape: (2,), w shape: (2,)

1. Array Addition:
x + y =
[[ 6  8]
 [10 13]]

2. Array Subtraction:
x - y =
[[-4 -4]
 [-4 -3]]
y - x =
[[4 4]
 [4 3]]

3. Array Multiplication with scalars:
2 * x =
[[ 2  4]
 [ 6 10]]
3 * y =
[[15 18]
 [21 24]]
0.5 * v = [4.5 5. ]

4. Element-wise Square:
x² =
[[ 1  4]
 [ 9 25]]
y² =
[[25 36]
 [49 64]]
v² = [ 81 100]

Using np.square():
np.square(x) =
[[ 1  4]
 [ 9 25]]

5. Dot Products:
v · w = 219
Calculation: (9×11) + (10×12) = 99 + 120 = 219

x · v = [29 77]
Calculation:
Row 1: (1×9) + (2×10) = 9 + 20 = 29
Row 2: (3×9) + (5×10) = 27 + 50 = 77

x · y = 
[[19 22]
 [50 58]]
Calculation:
Element [0,0]: (1×5) + (2×7) = 5 + 14 = 19
Element [0,1]: (1×6) + (2×8) = 6 + 16 = 22
Element [1,0]: (3×5) + (5×7) = 15 + 35 = 50
Element [1,1]: (3×6) + (5×8) = 18 + 5×8 = 58

6. Array Concatenation:
Concatenate x and y along rows (axis=0):
[[1 2]
 [3 5]
 [5 6]

In [ ]:
#Problem - 4: Matrix Operations
import numpy as np

# Initialize matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("Initial Matrices:")
print(f"A = \n{A}")
print(f"B = \n{B}")

# 1. Prove A.A⁻¹ = I
print("\n1. Prove A.A⁻¹ = I:")
print("=" * 50)

try:
    # Calculate inverse of A
    A_inv = np.linalg.inv(A)
    print(f"A⁻¹ = \n{A_inv}")
    
    # Multiply A with its inverse
    identity_check = np.dot(A, A_inv)
    print(f"\nA × A⁻¹ = \n{identity_check}")
    
    # Create actual identity matrix for comparison
    I = np.eye(2)
    print(f"\nActual Identity matrix I = \n{I}")
    
    # Check if they are close (due to floating point precision)
    is_identity = np.allclose(identity_check, I)
    print(f"\nIs A × A⁻¹ equal to I? {is_identity}")
    print(f"Maximum difference: {np.max(np.abs(identity_check - I)):.10f}")
    
except np.linalg.LinAlgError:
    print("Matrix A is singular, cannot compute inverse")

# 2. Prove AB ≠ BA
print("\n2. Prove AB ≠ BA:")
print("=" * 50)

AB = np.dot(A, B)
BA = np.dot(B, A)

print(f"A × B = \n{AB}")
print(f"B × A = \n{BA}")

are_equal = np.array_equal(AB, BA)
print(f"\nIs AB equal to BA? {are_equal}")

if not are_equal:
    print("✓ Proved: Matrix multiplication is not commutative (AB ≠ BA)")

# 3. Prove (AB)ᵀ = BᵀAᵀ
print("\n3. Prove (AB)ᵀ = BᵀAᵀ:")
print("=" * 50)

AB_transpose = AB.T
print(f"(AB)ᵀ = \n{AB_transpose}")

B_transpose = B.T
A_transpose = A.T
BTA_transpose = np.dot(B_transpose, A_transpose)
print(f"BᵀAᵀ = \n{BTA_transpose}")

are_transpose_equal = np.array_equal(AB_transpose, BTA_transpose)
print(f"\nIs (AB)ᵀ equal to BᵀAᵀ? {are_transpose_equal}")

if are_transpose_equal:
    print("✓ Proved: (AB)ᵀ = BᵀAᵀ")

print("\n" + "=" * 70)
print("Solving System of Linear Equations")
print("=" * 70)

# System of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3  
# 3x + y - z = 9

print("System of equations:")
print("2x - 3y + z = -1")
print("x - y + 2z = -3")
print("3x + y - z = 9")

# Represent in matrix form: AX = B
A_matrix = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])

B_vector = np.array([-1, -3, 9])

print(f"\nMatrix A = \n{A_matrix}")
print(f"Vector B = {B_vector}")

# Method 1: Using inverse method (X = A⁻¹B)
print("\nMethod 1: Using Inverse Method (X = A⁻¹B)")
print("-" * 50)

try:
    # Calculate inverse of A
    A_inv = np.linalg.inv(A_matrix)
    print(f"A⁻¹ = \n{A_inv}")
    
    # Solve for X
    X_solution = np.dot(A_inv, B_vector)
    print(f"\nSolution X = A⁻¹B = {X_solution}")
    
    # Extract variables
    x, y, z = X_solution
    print(f"\nSolution:")
    print(f"x = {x:.2f}")
    print(f"y = {y:.2f}") 
    print(f"z = {z:.2f}")
    
    # Verify the solution
    print(f"\nVerification:")
    eq1 = 2*x - 3*y + z
    eq2 = x - y + 2*z
    eq3 = 3*x + y - z
    print(f"Equation 1: 2({x:.2f}) - 3({y:.2f}) + ({z:.2f}) = {eq1:.2f} (Expected: -1)")
    print(f"Equation 2: ({x:.2f}) - ({y:.2f}) + 2({z:.2f}) = {eq2:.2f} (Expected: -3)")
    print(f"Equation 3: 3({x:.2f}) + ({y:.2f}) - ({z:.2f}) = {eq3:.2f} (Expected: 9)")
    
except np.linalg.LinAlgError:
    print("Matrix A is singular, cannot use inverse method")

# Method 2: Using np.linalg.solve (recommended method)
print("\n" + "=" * 50)
print("Method 2: Using np.linalg.solve (Recommended)")
print("-" * 50)

try:
    X_solution_solve = np.linalg.solve(A_matrix, B_vector)
    print(f"Solution using np.linalg.solve = {X_solution_solve}")
    x_s, y_s, z_s = X_solution_solve
    print(f"x = {x_s:.2f}, y = {y_s:.2f}, z = {z_s:.2f}")
    
except np.linalg.LinAlgError:
    print("Matrix is singular, cannot solve")

print("\n" + "=" * 70)
print("Exploring np.linalg functions")
print("=" * 70)

# Additional linalg functions demonstration
print("\nAdditional np.linalg functions:")

# Determinant
det_A = np.linalg.det(A_matrix)
print(f"Determinant of A: {det_A:.2f}")

# Rank
rank_A = np.linalg.matrix_rank(A_matrix)
print(f"Rank of A: {rank_A}")

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A_matrix)
print(f"Eigenvalues of A: {eigenvalues}")
print(f"Eigenvectors of A: \n{eigenvectors}")

# Matrix norm
norm_A = np.linalg.norm(A_matrix)
print(f"Frobenius norm of A: {norm_A:.2f}")

# Condition number
cond_A = np.linalg.cond(A_matrix)
print(f"Condition number of A: {cond_A:.2f}")

print("\n" + "=" * 70)
print("Verification of Matrix Properties")
print("=" * 70)

# Additional verification
print("\nAdditional matrix property verification:")

# Verify (A⁻¹)⁻¹ = A
A_inv_inv = np.linalg.inv(A_inv)
print(f"(A⁻¹)⁻¹ = A? {np.allclose(A_inv_inv, A_matrix)}")

# Verify (Aᵀ)ᵀ = A
A_T_T = A_matrix.T.T
print(f"(Aᵀ)ᵀ = A? {np.array_equal(A_T_T, A_matrix)}")

# Verify determinant properties
det_A_inv = np.linalg.det(A_inv)
print(f"det(A⁻¹) = 1/det(A)? {np.allclose(det_A_inv, 1/det_A)}")

# Solve using least squares (for overdetermined systems)
print("\nLeast squares solution (alternative method):")
X_lstsq = np.linalg.lstsq(A_matrix, B_vector, rcond=None)[0]
print(f"Least squares solution: {X_lstsq}")